spring:
  application:
    name: ranker
  datasource:
    url: jdbc:mysql://localhost:3306/ranker
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
jwt:
  secretKey: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437 # must be a 64 character long random string
  expirationTime: 36000000
  tokenHeader: X-Auth-Token